import {
  DescriptionOutlined as OrdersIcon,
  LocalOfferOutlined as KOTsIcon,
  GroupsOutlined as CustomerIcon,
  AttachMoneyOutlined as CashPrizeIcon,
  AccountBalanceWalletOutlined as ExpensesIcon,
  PriceCheckOutlined as WithdrawalIcon,
  AirlineStopsOutlined as CashTopUpIcon,
  Inventory2Outlined as InventoryIcon,
  NotificationsNoneOutlined as NotificationIcon,
  TableBarOutlined as TableIcon,
  SyncOutlined as ManualSyncIcon,
  ContactSupportOutlined as HelpIcon,
  GridViewOutlined as LiveViewIcon,
  PaymentsOutlined as DualPaymentIcon,
  TranslateOutlined as LanguageIcon,
  BadgeOutlined as BillingUserIcon,
  CurrencyExchangeOutlined as CurrencyConversionIcon,
  RestaurantMenu as RestaurantMenuIcon,
  LocalPrintshop as LocalPrintshopIcon,
  ArticleOutlined as ArticleOutlinedIcon,
  PercentOutlined as PercentOutlinedIcon,
  PresentToAllOutlined as PresentToAllOutlinedIcon,
  SettingsOutlined as SettingsOutlinedIcon,
  CardTravel as CardTravelIcon,
  MenuBook as MenuBookIcon,
  Contactless as ContactlessIcon,
  Contactless as LeakAddOutlinedIcon,
} from '@mui/icons-material';

export const SectionA = [
  {
    title: 'Orders',
    IconName: OrdersIcon,
    key: 'orders',
    link: '/configuration/order',
  },
  {
    title: 'KOTs',
    IconName: KOTsIcon,
    key: 'kots',
    link: '/configuration/kot-listing',
  },
  {
    title: 'Customer',
    IconName: CustomerIcon,
    key: 'customer',
    link: '/configuration/customer-listing',
  },
  {
    title: 'Cash Prize',
    IconName: CashPrizeIcon,
    key: 'cashPrize',
    link: '/configuration/cashprize-listing',
  },
  {
    title: 'Expenses',
    IconName: ExpensesIcon,
    key: 'expenses',
    link: '/configuration/expense-listing',
  },
  {
    title: 'Withdrawal',
    IconName: WithdrawalIcon,
    key: 'withdrawal',
    link: '/configuration/withdrawal-listing',
  },
  {
    title: 'Cash Top-Up',
    IconName: CashTopUpIcon,
    key: 'cashTopUp',
    link: '/configuration/cash-top-up-listing',
  },
  {
    title: 'Inventory',
    IconName: InventoryIcon,
    key: 'inventory',
    link: '/configuration/inventory-listing',
  },
  {
    title: 'Notification',
    IconName: NotificationIcon,
    key: 'notification',
    link: '/configuration/notification-listing',
  },
  {
    title: 'Table',
    IconName: TableIcon,
    key: 'table',
    link: '/',
  },
  {
    title: 'Manual Sync',
    IconName: ManualSyncIcon,
    key: 'manualSync',
    link: '/configuration/order',
  },
  {
    title: 'Help',
    IconName: HelpIcon,
    key: 'help',
    link: '/configuration/order',
  },
  {
    title: 'Live View',
    IconName: LiveViewIcon,
    key: 'liveView',
    link: '/configuration/order',
  },
  {
    title: 'Dual Payment',
    IconName: DualPaymentIcon,
    key: 'dualPayment',
    link: '/configuration/order',
  },
  {
    title: 'Language Profile',
    IconName: LanguageIcon,
    key: 'languageProfile',
    link: '/configuration/order',
  },
  {
    title: 'Billing User Profile',
    IconName: BillingUserIcon,
    key: 'billingUserProfile',
    link: '/configuration/billing-user-profile',
  },
  {
    title: 'Currency Conversion',
    IconName: CurrencyConversionIcon,
    key: 'currencyConversion',
    link: '/configuration/order',
  },
];

export const SectionB = [
  {
    title: 'Menu',
    IconName: RestaurantMenuIcon,
    key: 'menu',
    link: '/configuration/menu',
  },
  {
    title: 'Bill/KOT Print',
    IconName: LocalPrintshopIcon,
    key: 'bill/kOT print',
    link: '/configuration/bill-kot-print',
  },
  {
    title: 'Tax',
    IconName: ArticleOutlinedIcon,
    key: 'tax',
    link: '/configuration/tax',
  },
  {
    title: 'Discount',
    IconName: PercentOutlinedIcon,
    key: 'discount',
    link: '/configuration/discount',
  },
  {
    title: 'Billing Screen',
    IconName: PresentToAllOutlinedIcon,
    key: 'billing screen',
    link: '/configuration/billing-screen',
  },
  {
    title: 'Setting',
    IconName: SettingsOutlinedIcon,
    key: 'setting',
    link: '/configuration/setting',
  },
  {
    title: 'Online Order Configuration',
    IconName: CardTravelIcon,
    key: 'online order configuration',
    link: '/*',
  },
  {
    title: 'Menu Item On/Off',
    IconName: MenuBookIcon,
    key: 'menu item on/off',
    link: '/*',
  },
  {
    title: 'Google Pay Configuration',
    IconName: ContactlessIcon,
    key: 'google pay configuration',
    link: '/*',
  },
  {
    title: 'Service Renewal',
    IconName: LeakAddOutlinedIcon,
    key: 'service renewal',
    link: '/*',
  },
];
