export const Menu = [
  {
    id: 1,
    key: 'south',
    item: 'South',
    subitem: [
      {
        id: 1,
        item: 'Dosa',
        price: 100,
        quantity: 1,
        isVeg: true,
        addOn: [
          {
            id: 1,
            item: 'spicy',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
          {
            id: 2,
            item: 'Masala',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
          {
            id: 3,
            item: 'spicy',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
          {
            id: 4,
            item: 'Masala',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
          {
            id: 5,
            item: 'spicy',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
          {
            id: 6,
            item: 'Masala',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
          {
            id: 7,
            item: 'spicy',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
          {
            id: 8,
            item: 'Masala',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
          {
            id: 9,
            item: 'spicy',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
          {
            id: 10,
            item: 'Masala',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
        ],
      },
      {
        id: 2,
        item: 'Idli',
        price: 50,
        quantity: 1,
        isVeg: true,
        addOn: [],
      },
    ],
  },
  {
    id: 2,
    key: 'north',
    item: 'North',
    subitem: [
      {
        id: 1,
        item: 'Chicken',
        price: 350,
        quantity: 1,
        isVeg: false,
        addOn: [
          {
            id: 1,
            item: 'extra gravy',
            quantity: 1,
            price: 20,
            isVeg: false,
          },
        ],
      },
      {
        id: 2,
        item: 'Paneer',
        price: 250,
        quantity: 1,
        isVeg: true,
        addOn: [
          {
            id: 1,
            item: 'extra gravy',
            quantity: 1,
            price: 20,
            isVeg: true,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    key: 'italian',
    item: 'Italian',
    subitem: [
      {
        id: 1,
        item: 'Pizza',
        price: 300,
        quantity: 1,
        isVeg: true,
        addOn: [
          {
            id: 1,
            item: 'extra cheeze',
            quantity: 1,
            price: 40,
            isVeg: true,
          },
        ],
      },
      {
        id: 2,
        item: 'Pasta',
        price: 90,
        quantity: 1,
        isVeg: true,
        addOn: [],
      },
      {
        id: 3,
        item: 'Burgar',
        price: 70,
        quantity: 1,
        isVeg: true,
        addOn: [
          {
            id: 1,
            item: 'extra veg',
            quantity: 1,
            price: 30,
            isVeg: true,
          },
        ],
      },
      {
        id: 4,
        item: 'Pizza 2',
        price: 325,
        quantity: 1,
        isVeg: false,
        addOn: [
          {
            id: 1,
            item: 'extra cheeze',
            quantity: 1,
            price: 40,
            isVeg: false,
          },
        ],
      },
      {
        id: 5,
        item: 'Pasta 2',
        price: 95,
        quantity: 1,
        isVeg: true,
        addOn: [],
      },
      {
        id: 6,
        item: 'Burgar 2',
        price: 65,
        quantity: 1,
        isVeg: false,
        addOn: [],
      },
    ],
  },
  {
    id: 4,
    key: 'veg',
    item: 'Veg',
    subitem: [
      {
        id: 1,
        item: 'Salad',
        price: 50,
        quantity: 1,
        isVeg: true,
        addOn: [],
      },
    ],
  },
];
